In [58]:
from numpy import array
import numpy as np

In [6]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [67]:
a_array = np.array(range(12))
a_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [2]:
b = np.arange(12).reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [39]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### Column-wise

- 3부분으로 배열 나누기

In [7]:
np.hsplit(a, 3)

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

In [53]:
a.shape

(12,)

In [54]:
np.split(a, 3, axis = 0) 

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

In [55]:
np.split(a, 3, axis = 1) 

IndexError: tuple index out of range

- `axis = 0` 이 의미하는 바는 shape[0]
- `axis = 1` dl 의미하는 바는 shape[1]
- `axis =1` 일 때 오류가 나는 이유는 a.shape (12, ) 으로 tuple index out of range 

<br>

- **인덱스** 활용하기

In [8]:
np.hsplit(a, [3,6])

[array([0, 1, 2]), array([3, 4, 5]), array([ 6,  7,  8,  9, 10, 11])]

- `[3, 6]` 은 인덱스로 [0:3], [3:6], [6:] 과 같은 의미이다.

In [16]:
np.hsplit(a, [0,3])

[array([], dtype=int32),
 array([0, 1, 2]),
 array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])]

- `[0,3]` = [], [0:3], [3:]

In [30]:
np.hsplit(b, [1,2])

[array([[0],
        [3],
        [6],
        [9]]), array([[ 1],
        [ 4],
        [ 7],
        [10]]), array([[ 2],
        [ 5],
        [ 8],
        [11]])]

In [31]:
np.hsplit(b, [1,2])[0]

array([[0],
       [3],
       [6],
       [9]])

In [32]:
np.hsplit(b, [1,2])[1]

array([[ 1],
       [ 4],
       [ 7],
       [10]])

In [33]:
np.hsplit(b, [1,2])[2]

array([[ 2],
       [ 5],
       [ 8],
       [11]])

<br>

### Row-wise

In [3]:
np.vsplit(b,2)

[array([[0, 1, 2],
        [3, 4, 5]]), array([[ 6,  7,  8],
        [ 9, 10, 11]])]

In [37]:
np.split(b, 2, axis = 0)

[array([[0, 1, 2],
        [3, 4, 5]]), array([[ 6,  7,  8],
        [ 9, 10, 11]])]

In [71]:
np.split(b, 2, axis = 1)

ValueError: array split does not result in an equal division

In [79]:
b.shape

(4, 3)

In [43]:
np.split(c,2, axis = 1)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

<br>

- 인덱스 활용

In [81]:
np.split(b, [0], 1)

[array([], shape=(4, 0), dtype=int32), array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])]

In [72]:
np.split(b, [0], 0)

[array([], shape=(0, 3), dtype=int32), array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])]

In [11]:
np.split(b, [1], 1)#

[array([[0],
        [3],
        [6],
        [9]]), array([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11]])]

In [73]:
np.split(b, [1], 0)

[array([[0, 1, 2]]), array([[ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])]

In [12]:
np.split(b, [2], 1)

[array([[ 0,  1],
        [ 3,  4],
        [ 6,  7],
        [ 9, 10]]), array([[ 2],
        [ 5],
        [ 8],
        [11]])]

In [75]:
np.split(b, [2], 0)

[array([[0, 1, 2],
        [3, 4, 5]]), array([[ 6,  7,  8],
        [ 9, 10, 11]])]

In [13]:
np.split(b, [3], 1)

[array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]), array([], shape=(4, 0), dtype=int32)]

In [76]:
np.split(b, [3], 0)

[array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]), array([[ 9, 10, 11]])]

In [14]:
np.split(b, [4], 1)

[array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]), array([], shape=(4, 0), dtype=int32)]

In [77]:
np.split(b, [4], 0)

[array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]), array([], shape=(0, 3), dtype=int32)]

In [78]:
np.split(b, [5], 0)

[array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]), array([], shape=(0, 3), dtype=int32)]