In [1]:
import numpy as np

In [3]:
a = np.arange(10, 20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [28]:
b = np.array([[12, 9, 83, 40],
              [73, 59, 24, 2],
              [44, 3, 18, 65]])
b

array([[12,  9, 83, 40],
       [73, 59, 24,  2],
       [44,  3, 18, 65]])

<br>

### np.where
- 인덱스반환

In [19]:
np.where(a> 15)

(array([6, 7, 8, 9], dtype=int64),)

In [17]:
np.where(a == 10)

(array([0], dtype=int64),)

In [30]:
np.where(b>20)

(array([0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([2, 3, 0, 1, 2, 0, 3], dtype=int64))

In [31]:
b[np.where(b> 20)]

array([83, 40, 73, 59, 24, 44, 65])

<br>

#### np.where() 값 변경

`np.where(condition, T, F)`

In [9]:
np.where(a > 15, True, False)

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [8]:
sum(np.where(a > 15, True, False))

4

<br>

### 조건에 맞는 값 찾기

In [10]:
np.max(a)

# max() 가능

19

In [12]:
np.min(a)

# min() 가능

10

In [45]:
np.sort(a)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [32]:
np.max(b)

83

In [33]:
np.min(b)

2

In [35]:
np.sort(b, axis = 1)

array([[ 9, 12, 40, 83],
       [ 2, 24, 59, 73],
       [ 3, 18, 44, 65]])

In [36]:
np.sort(b, axis =0)

array([[12,  3, 18,  2],
       [44,  9, 24, 40],
       [73, 59, 83, 65]])

<br>

### 조건에 맞는 인덱스 찾기

In [11]:
np.argmax(a)

9

In [13]:
np.argmin(a)

0

In [14]:
np.argsort(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)