In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder, OneHotEncoder

C:\Users\user\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\user\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


<br>

### 0. Data 준비

In [2]:
data = pd.DataFrame([
    ['green', 'M', 10.1, 'class_1'],
    ['red', 'S', 22, 'class_2'],
    ['blue', 'XL', 15, 'class_1'],
    ['yellow', 'L', 20, 'class_2']
])

data.columns = ['color', 'size', 'price', 'label']

In [3]:
data

color size  price    label
0   green    M   10.1  class_1
1     red    S   22.0  class_2
2    blue   XL   15.0  class_1
3  yellow    L   20.0  class_2

<br>

### 1. LabelEncoder()

In [45]:
class_le = LabelEncoder()
y_label = class_le.fit_transform(data['label'].values)

In [46]:
y_label

array([0, 1, 0, 1])

<br>

#### 참고) inverse_transform = 라벨링을 다시 문자열(기존 값)로 바꿔 줌

In [6]:
class_le.inverse_transform(y_label)

array(['class_1', 'class_2', 'class_1', 'class_2'], dtype=object)

<br>

### 2. pd.factorize()

In [9]:
y_encoded, y_class = pd.factorize(data['label'])

In [10]:
y_encoded

array([0, 1, 0, 1], dtype=int64)

In [11]:
y_class

Index(['class_1', 'class_2'], dtype='object')

In [47]:
data['label_enco'] = y_encoded
data

color size  price    label  label_enco
0   green    M   10.1  class_1           0
1     red    S   22.0  class_2           1
2    blue   XL   15.0  class_1           0
3  yellow    L   20.0  class_2           1

In [53]:
data.drop('label_enco', axis =1, inplace = True)

<br>

### 3. pd.get_dummies()

In [48]:
dm = pd.get_dummies(data['label'])

In [49]:
dm

class_1  class_2
0        1        0
1        0        1
2        1        0
3        0        1

In [54]:
dm_2 = pd.get_dummies(data)
dm_2

price  color_blue  color_green  color_red  color_yellow  size_L  size_M  \
0   10.1           0            1          0             0       0       1   
1   22.0           0            0          1             0       0       0   
2   15.0           1            0          0             0       0       0   
3   20.0           0            0          0             1       1       0   

   size_S  size_XL  label_class_1  label_class_2  
0       0        0              1              0  
1       1        0              0              1  
2       0        1              1              0  
3       0        0              0              1

<br>

### 4. OneHotEncoder()

- onehotencoder() 적용하기 전에, onehotencoding 하고 싶은 변수를 reshape 을 통해서 1차원으로 만들어 주어야 함
- 결과 역시 toarray()를 통해서 확인해야 함

In [23]:
class_one = OneHotEncoder()
y_one = class_one.fit_transform(np.array(data['label']).reshape(-1, 1))
y_one

<4x2 sparse matrix of type '<class 'numpy.float64'>'
	with 4 stored elements in Compressed Sparse Row format>

In [24]:
y_one.toarray()

array([[1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.]])

<br>

#### 4.1 sparse = False
- 해당 옵션을 활용할 경우, toarray() 하지 않아도 됨

In [30]:
class_one = OneHotEncoder(sparse = False)
y_one = class_one.fit_transform(np.array(data['label']).reshape(-1, 1))
y_one

array([[1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.]])

#### 4.2 categorical_features
- `categorical_features` 매개변수 

In [36]:
class_one = OneHotEncoder(categorical_features = [0],sparse = False)
y_one = class_one.fit_transform(np.array(data['price'].values).reshape(-1, 1))
y_one

C:\Users\user\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


array([[1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])